#!/usr/bin/env node
import { writeFileSync } from "node:fs";
import path from "node:path";
import {
  IMPROVEMENTS_DIR,
  listFindingFiles,
  markdownTable,
  oneLineTitle,
  parseFinding,
} from "./improvements-lib.mjs";

const order = ["skills", "stellar-light-scout", "stellar-docs", "lumenloop"];
const findings = listFindingFiles().map(parseFinding);
const rowsByService = new Map(order.map((service) => [service, []]));

for (const finding of findings) {
  const fm = finding.frontmatter;
  rowsByService.get(fm.service)?.push([
    fm.id,
    oneLineTitle(finding),
    fm.status,
    fm.discovered,
    (fm.recurrences ?? []).length,
  ]);
}

const lines = [
  "# Improvements Index",
  "",
  "> Generated by `npm run improvements:index`. Do not hand-edit.",
  "",
  `Total findings: ${findings.length}`,
  "",
];

for (const service of order) {
  const rows = rowsByService.get(service) ?? [];
  lines.push(`## ${service}`);
  lines.push("");
  lines.push(markdownTable(rows, ["id", "title", "status", "discovered", "recurrences"]));
  lines.push("");
}

writeFileSync(path.join(IMPROVEMENTS_DIR, "INDEX.md"), `${lines.join("\n").trimEnd()}\n`);
console.log(`wrote improvements/INDEX.md (${findings.length} findings)`);
